rules:
    semi: error
    quotes: [error, single, {allowTemplateLiterals: true}]
    indent: [error, 4]
    linebreak-style: [error, unix]
    no-unused-vars: warn
env:
    es6: true
    node: true
extends: eslint:recommended